"""Arabic edition of the Twaa financial model.
Called by build_model.py when TWAA_LANG=ar: translates every label, note and formula text literal, renames the sheets
(and every formula reference to them), translates chart titles/series and sets each sheet right-to-left.
Formulas and numbers are untouched, so the Arabic workbook computes exactly the same results as the English one."""
import re

SHEETS = {"Summary": "الملخص", "Assumptions": "الافتراضات", "Model": "النموذج", "Annual": "السنوي", "Unit Economics": "اقتصاديات الوحدة", "Revenue Streams": "مصادر الإيراد"}

T = {
 "   Share of orders from Twaa+ members": "   حصة الطلبات من مشتركي توّا+", "   of which Abu El Matamir": "   منها أبو المطامير", "   of which acquisition marketing": "   منها تسويق الاستحواذ", "   of which customer promotions": "   منها عروض العملاء", "   of which product margin": "   منها هامش المنتجات", "   of which rider cost": "   منها تكلفة المندوب",
 "% GMV": "% من GMV", "% MP GMV": "% من GMV السوق", "% digital GMV": "% من GMV الإلكتروني", "% food GMV": "% من GMV الأكل", "% hub GMV": "% من GMV الهب", "(spare slot)": "(خانة احتياطية)", "0/1": "0/1",
 "1 · Scenario": "1 · السيناريو", "1. Change inputs only on the Assumptions sheet (blue text; yellow = key levers).": "1. غيّر المدخلات في ورقة الافتراضات فقط (النص الأزرق؛ الأصفر = الروافع الرئيسية).", "1. Product sales (owned inventory)": "1. مبيعات المنتجات (مخزون مملوك)",
 "10 · Expansion to other Beheira markazes (hub-in-a-box playbook)": "10 · التوسع لمراكز البحيرة الأخرى (دليل هب في صندوق)", "11–12% of merchant order value": "11–12% من قيمة طلب التاجر", "17–18% of food order value": "17–18% من قيمة طلب الأكل",
 "2 · Timeline & market": "2 · الجدول الزمني والسوق", "2. Marketplace & pharmacy commission": "2. عمولة السوق والصيدليات", "2027 (pilot deals)": "2027 (صفقات تجريبية)", "2–3 engineers + QA, or vendor maintenance.": "2–3 مهندسين + اختبار جودة، أو صيانة من مورّد.",
 "3 · Customer acquisition & retention": "3 · استحواذ العملاء والاحتفاظ بهم", "3. Food commission": "3. عمولة المطاعم", "3. Model = monthly engine (Oct 2026 – Dec 2031). Annual, Unit Economics and Revenue Streams roll it up.": "3. النموذج = محرك شهري (أكتوبر 2026 – ديسمبر 2031). أوراق السنوي واقتصاديات الوحدة ومصادر الإيراد تجمّعه.",
 "4 · Basket & category mix": "4 · السلة ومزيج الأقسام", "4. Colours: blue input · black formula · green link to another sheet. All values nominal EGP ex-VAT.": "4. الألوان: أزرق مدخل · أسود معادلة · أخضر ربط بورقة أخرى. كل القيم بالجنيه الاسمي بدون ضريبة القيمة المضافة.", "4. Delivery fees": "4. رسوم التوصيل",
 "5 · Revenue streams (pricing & take rates)": "5 · مصادر الإيراد (التسعير ونسب الاستقطاع)", "5. Service fees": "5. رسوم الخدمة", "6 · Variable costs (per order / % of GMV)": "6 · التكاليف المتغيرة (لكل طلب / % من GMV)", "6. Twaa+ subscriptions": "6. اشتراكات توّا+",
 "7 · Fixed operating costs (monthly)": "7 · التكاليف التشغيلية الثابتة (شهرياً)", "7. Delivery-as-a-Service fees": "7. رسوم التوصيل كخدمة", "8 · Capital expenditure & depreciation": "8 · الإنفاق الرأسمالي والإهلاك", "8. Retail media": "8. إعلانات التطبيق", "8. Retail media (sponsored placement)": "8. إعلانات التطبيق (أماكن مدفوعة)",
 "9 · Working capital, tax & funding": "9 · رأس المال العامل والضريبة والتمويل", "9. Supplier back margin": "9. حوافز الموردين",
 "Abu Hummus — أبو حمص": "أبو حمص", "Badr — بدر": "بدر", "Delengat — الدلنجات": "الدلنجات", "Hosh Issa — حوش عيسى": "حوش عيسى", "Kom Hamada — كوم حمادة": "كوم حمادة",
 "Acquisition marketing": "تسويق الاستحواذ", "Acquisition marketing spend — Abu El Matamir": "إنفاق تسويق الاستحواذ — أبو المطامير", "Acquisition spend — group": "إنفاق الاستحواذ — المجموعة", "Acquisition spend — launch month (Feb 2027)": "إنفاق الاستحواذ — شهر الإطلاق (فبراير 2027)", "Acquisition spend — month 3 (Mar 2027)": "إنفاق الاستحواذ — الشهر الثالث (مارس 2027)", "Acquisition spend — monthly run-rate thereafter": "إنفاق الاستحواذ — المعدل الشهري بعد ذلك", "Acquisition spend — pilot month (Jan 2027)": "إنفاق الاستحواذ — شهر التجربة (يناير 2027)",
 "Active": "نشط", "Active customers (December)": "العملاء النشطون (ديسمبر)", "Active customers — Abu El Matamir": "العملاء النشطون — أبو المطامير", "Active customers — group": "العملاء النشطون — المجموعة",
 "Added to yearly retention (capped at 95%).": "تُضاف للاحتفاظ السنوي (بحد أقصى 95%).", "Applied to hub share of orders.": "تُطبّق على حصة الهب من الطلبات.",
 "Apr 2027": "أبريل 2027", "Apr 2028. Fit-out paid the month before.": "أبريل 2028. التجهيز يُدفع في الشهر السابق.", "Apr 2029": "أبريل 2029", "Apr 2029.": "أبريل 2029.", "Apr 2030": "أبريل 2030",
 "Assumption year (1=2027)": "سنة الافتراض (1 = 2027)", "Assumption: rising as early adopters are exhausted. Validate after pilot.": "افتراض: ترتفع بعد استنفاد المتبنين الأوائل. تتأكد بعد التجربة.", "Average delivery fee charged (city + village blend)": "متوسط رسوم التوصيل المحصّلة (مزيج المدينة والقرى)", "Average household size": "متوسط حجم الأسرة",
 "Average order value": "متوسط قيمة الطلب", "Average order value (AOV)": "متوسط قيمة الطلب (AOV)", "Average order value (GMV per order)": "متوسط قيمة الطلب (GMV للطلب)",
 "Base": "الأساسي", "Basket size (AOV) multiplier": "معامل حجم السلة (AOV)", "Blended CAC": "CAC المجمّع", "Blended CAC (paid acquisition incl. first-order discount)": "CAC المجمّع (استحواذ مدفوع شامل خصم أول طلب)", "Blended CAC, Year 3": "CAC المجمّع، السنة الثالثة",
 "Blue = input you can change · Yellow = key lever · Values in nominal EGP (≈10–12%/yr inflation already inside yearly inputs), ex-VAT. 2027 = Year 1 (pilot Jan, public launch Feb). Horizon: Oct 2026 – Dec 2031.": "الأزرق = مدخل قابل للتغيير · الأصفر = رافعة رئيسية · القيم بالجنيه الاسمي (تضخم ≈10–12% سنوياً داخل المدخلات السنوية)، بدون ضريبة القيمة المضافة. 2027 = السنة الأولى (تجربة يناير، إطلاق عام فبراير). الأفق: أكتوبر 2026 – ديسمبر 2031.",
 "Brand & community marketing": "تسويق العلامة والمجتمع", "Brand & community marketing (non-acquisition)": "تسويق العلامة والمجتمع (غير الاستحواذ)", "Brand-funded visibility; sold to FMCG distributors.": "ظهور ممول من العلامات؛ يُباع لموزعي السلع الاستهلاكية.",
 "Buy from distributors, sell at shelf price; front margin 16% → 21% (private label from 2029)": "شراء من الموزعين والبيع بسعر الرف؛ هامش أمامي 16% ← 21% (علامة خاصة من 2029)",
 "CAC payback (Y3)": "استرداد CAC (السنة 3)", "CAC payback, Year 3 (months of contribution)": "استرداد CAC، السنة الثالثة (شهور مساهمة)", "COD dominant at launch.": "الكاش عند الاستلام هو الأساس عند الإطلاق.", "Calendar year": "السنة الميلادية",
 "Capex": "الإنفاق الرأسمالي", "Capex — hubs & rider kit": "الإنفاق الرأسمالي — الهبات وعدة المناديب", "Capex — platform build": "الإنفاق الرأسمالي — بناء المنصة", "Cash": "النقدية", "Cash balance (December)": "رصيد النقدية (ديسمبر)", "Cash balance (end of month)": "رصيد النقدية (نهاية الشهر)",
 "Central costs (tech, leadership & G&A, brand)": "التكاليف المركزية (تقنية، إدارة ومصروفات عمومية، علامة)", "Central costs (technology, leadership & G&A, brand)": "التكاليف المركزية (التقنية والإدارة والمصروفات العمومية والعلامة)", "Change in working capital": "التغير في رأس المال العامل", "Change this one cell to switch the whole model.": "غيّر الخلية دي بس لتبديل النموذج كله.",
 "Charged to merchants / partner pharmacies on each order.": "تُحصّل من التجار والصيدليات الشريكة على كل طلب.", "Charged to restaurants.": "تُحصّل من المطاعم.", "Chart data — gross profit by stream (EGP)": "بيانات الرسم — مجمل الربح حسب المصدر (ج.م)", "Check vs Annual gross profit": "مطابقة مع مجمل الربح السنوي", "Check: mix sums to 100%": "تحقق: مجموع المزيج 100%",
 "Chillers and freezers run 24/7.": "الثلاجات والفريزرات شغالة 24 ساعة.", "City 10–15, villages 20–30. Free above basket threshold.": "المدينة 10–15، القرى 20–30. مجاني فوق حد السلة.", "City centre first, villages zone by zone (hub 2 and 3 extend reach).": "وسط المدينة أولاً، ثم القرى منطقة منطقة (الهب 2 و3 يوسّعان الوصول).", "Cloud, maps, SMS gateway, tools": "السحابة والخرائط وبوابة الرسائل والأدوات",
 "Conservative": "المتحفظ", "Content, sponsorships, village events.": "محتوى ورعايات وفعاليات قرى.", "Contribution margin": "هامش المساهمة", "Contribution per customer order": "المساهمة لكل طلب عميل", "Contribution per order": "المساهمة لكل طلب", "Contribution positive (1/0)": "مساهمة موجبة (1/0)", "Contribution-positive months so far": "شهور المساهمة الموجبة حتى الآن",
 "Corporate income tax rate": "سعر ضريبة دخل الشركات", "Cost of goods sold": "تكلفة البضاعة المباعة", "Cost of goods sold (owned inventory)": "تكلفة البضاعة المباعة (مخزون مملوك)", "Costs & profitability": "التكاليف والربحية", "Covers pre-launch, Abu El Matamir launch and villages until the growth round.": "تغطي ما قبل الإطلاق وإطلاق أبو المطامير والقرى حتى جولة النمو.",
 "Cumulative EBIT (loss carry-forward)": "EBIT التراكمي (ترحيل الخسائر)", "Cumulative free cash flow (before funding)": "التدفق النقدي الحر التراكمي (قبل التمويل)", "Cumulative hub capex": "الإنفاق الرأسمالي التراكمي للهبات", "Cumulative technology capex": "الإنفاق الرأسمالي التراكمي للتقنية",
 "Customer": "العميل", "Customer (in product price)": "العميل (ضمن سعر المنتج)", "Customer acquisition cost multiplier": "معامل تكلفة استحواذ العميل", "Customer lifetime contribution, Year 3 (CM/order × orders/month ÷ churn)": "مساهمة العميل مدى الحياة، السنة 3 (المساهمة/طلب × طلبات/شهر ÷ التسرب)",
 "Customer orders": "طلبات العملاء", "Customer orders per day": "طلبات العملاء في اليوم", "Customer orders — Abu El Matamir": "طلبات العملاء — أبو المطامير", "Customer orders — group": "طلبات العملاء — المجموعة", "Customer promotions": "عروض العملاء", "Customer promotions funded by Twaa (after first order)": "عروض العملاء الممولة من توّا (بعد أول طلب)", "Customer support team": "فريق خدمة العملاء", "Customers": "العملاء", "Customers & volume": "العملاء والحجم",
 "DaaS": "التوصيل كخدمة", "DaaS deliveries": "توصيلات التوصيل كخدمة", "DaaS deliveries (merchants' own orders)": "توصيلات التوصيل كخدمة (طلبات التجار الخاصة)", "DaaS fee per delivery (paid by merchant)": "رسوم التوصيل كخدمة للتوصيلة (يدفعها التاجر)", "DaaS fees (allocated per order)": "رسوم التوصيل كخدمة (موزعة على الطلب)", "DaaS starts in operating month": "التوصيل كخدمة يبدأ في الشهر التشغيلي",
 "Deliveries (customer drops + DaaS)": "التوصيلات (للعملاء + التوصيل كخدمة)", "Deliveries per customer order": "التوصيلات لكل طلب عميل", "Delivery fee": "رسوم التوصيل", "Delivery fees": "رسوم التوصيل", "Delivery-as-a-Service": "التوصيل كخدمة", "Delivery-as-a-Service deliveries per day (average)": "توصيلات التوصيل كخدمة في اليوم (متوسط)",
 "Depreciation & amortisation": "الإهلاك والاستهلاك", "Depreciation, tax & net income": "الإهلاك والضريبة وصافي الدخل", "Display only. Assumption — update to the current CBE rate.": "للعرض فقط. افتراض — حدّثه بسعر البنك المركزي الحالي.", "Distributors & brands": "الموزعون والعلامات",
 "EBIT": "EBIT", "EBITDA": "EBITDA", "EBITDA % of GMV": "EBITDA % من GMV", "EBITDA margin (% of GMV)": "هامش EBITDA (% من GMV)", "EBITDA per order": "EBITDA لكل طلب", "EBITDA positive (1/0)": "EBITDA موجبة (1/0)",
 "EGP": "ج.م", "EGP 17–25 blended; free above basket threshold": "17–25 ج.م في المتوسط؛ مجاني فوق حد السلة", "EGP 22–34 per delivery": "22–34 ج.م للتوصيلة", "EGP 3–6 per order, shown at checkout": "3–6 ج.م للطلب، ظاهرة عند الدفع", "EGP 49–72/month: free delivery, double points": "49–72 ج.م/شهر: توصيل مجاني ونقاط مضاعفة",
 "EGP per USD": "جنيه لكل دولار", "EGP/customer": "ج.م/عميل", "EGP/delivery": "ج.م/توصيلة", "EGP/month": "ج.م/شهر", "EGP/order": "ج.م/طلب",
 "ESTIMATE — verify with CAPMAS latest census before external use.": "تقدير — تحقق من آخر تعداد للجهاز المركزي للتعبئة العامة والإحصاء قبل الاستخدام الخارجي.",
 "Each new markaz replicates the Abu El Matamir ramp (same age curve × size factor) and shares central tech and management.": "كل مركز جديد بيكرر منحنى أبو المطامير (نفس منحنى العمر × معامل الحجم) ويشارك التقنية والإدارة المركزية.",
 "Egypt Income Tax Law 91/2005, standard rate 22.5%. Losses carried forward.": "قانون ضريبة الدخل المصري 91 لسنة 2005، السعر القياسي 22.5%. ترحيل الخسائر.", "Equity funding": "تمويل بالأسهم", "Equity funding received": "التمويل بالأسهم المستلم", "Estimate for rural Beheira; verify with CAPMAS.": "تقدير لريف البحيرة؛ تحقق من الجهاز المركزي للتعبئة العامة والإحصاء.", "Exchange rate for USD equivalents": "سعر الصرف لمعادلات الدولار",
 "Expansion markazes (same age curve × size factor)": "مراكز التوسع (نفس منحنى العمر × معامل الحجم)", "Expansion markazes in pre-launch month": "مراكز التوسع في شهر ما قبل الإطلاق", "Expansion markazes live": "مراكز التوسع العاملة", "Expansion switch (1 = on, 0 = Abu El Matamir only)": "مفتاح التوسع (1 = مفعّل، 0 = أبو المطامير فقط)",
 "FMCG brands & distributors": "علامات السلع الاستهلاكية والموزعون", "First EBITDA-positive month": "أول شهر EBITDA موجبة", "First contribution-positive month": "أول شهر مساهمة موجبة", "First-order discount sits inside CAC.": "خصم أول طلب ضمن CAC.", "Fixed costs & EBITDA": "التكاليف الثابتة و EBITDA", "Fixed costs & acquisition per order": "التكاليف الثابتة والاستحواذ لكل طلب",
 "Food": "الأكل", "Food commission": "عمولة المطاعم", "Free cash flow": "التدفق النقدي الحر", "Front margin on owned inventory": "الهامش الأمامي على المخزون المملوك", "Funding check": "فحص التمويل", "Funds the multi-markaz expansion; raise on proven Abu El Matamir unit economics.": "تموّل التوسع متعدد المراكز؛ تُجمع بعد إثبات اقتصاديات وحدة أبو المطامير.",
 "GMV": "قيمة الطلبات (GMV)", "GMV mix — Food (partner restaurants & Twaa kitchen)": "مزيج GMV — الأكل (مطاعم شريكة ومطبخ توّا)", "GMV mix — Marketplace (local merchants, partner pharmacies)": "مزيج GMV — السوق (تجار محليون وصيدليات شريكة)", "GMV mix — Twaa-owned inventory (hub)": "مزيج GMV — مخزون توّا المملوك (الهب)", "GMV — Twaa-owned inventory": "GMV — مخزون توّا المملوك", "GMV — food": "GMV — الأكل", "GMV — marketplace & pharmacy partners": "GMV — السوق والصيدليات الشريكة", "GMV — total": "GMV — الإجمالي",
 "GP 2027": "مجمل الربح 2027", "GP 2028": "مجمل الربح 2028", "GP 2029": "مجمل الربح 2029", "GP 2030": "مجمل الربح 2030", "GP 2031": "مجمل الربح 2031",
 "Groceries, household, cleaning, personal care.": "بقالة واحتياجات البيت ومنظفات وعناية شخصية.", "Gross profit": "مجمل الربح", "Gross profit % of GMV (take rate)": "مجمل الربح % من GMV (نسبة الاستقطاع)", "Gross profit by stream": "مجمل الربح حسب المصدر", "Gross profit per order (all streams)": "مجمل الربح للطلب (كل المصادر)",
 "Ground-floor unit ~150–250 m² in Abu El Matamir; get 3 quotes.": "وحدة دور أرضي حوالي 150–250 م² في أبو المطامير؛ خد 3 عروض أسعار.", "Group totals": "إجماليات المجموعة", "Growth round (Series A) amount": "قيمة جولة النمو (الجولة A)", "Growth round — operating month received": "جولة النمو — الشهر التشغيلي للاستلام",
 "Headline": "المؤشر الرئيسي", "Headline metrics": "المؤشرات الرئيسية", "Helpers": "حسابات مساعدة", "Hiring, training, supplier onboarding, legal, launch kit.": "تعيين وتدريب وضم موردين وقانوني وعدة إطلاق.", "Households inside delivery zones": "الأسر داخل مناطق التوصيل", "How it is applied": "طريقة التطبيق", "How to use this model": "طريقة استخدام النموذج",
 "Hub 1 fit-out (shelving, chillers, freezers, generator, scanners)": "تجهيز الهب 1 (أرفف وثلاجات وفريزرات ومولد وماسحات)", "Hub 2 (village micro-hub) opens in operating month": "الهب 2 (هب قرية صغير) يفتح في الشهر التشغيلي", "Hub 3 (village micro-hub) opens in operating month": "الهب 3 (هب قرية صغير) يفتح في الشهر التشغيلي", "Hub core team (per hub): manager, receiving, security": "الفريق الأساسي للهب (لكل هب): مدير واستلام وأمن",
 "Hub rent (per hub)": "إيجار الهب (لكل هب)", "Hub rent, utilities & core team": "إيجار الهب والمرافق والفريق الأساسي", "Hub rent/utilities/core team are counted via hubs operating.": "إيجار الهب والمرافق والفريق تُحسب حسب عدد الهبات العاملة.", "Hub utilities & electricity (per hub)": "مرافق وكهرباء الهب (لكل هب)", "Hubs operating": "الهبات العاملة", "Hubs operating (December)": "الهبات العاملة (ديسمبر)",
 "Income tax": "ضريبة الدخل", "Input": "المدخل", "Inventory": "المخزون", "Inventory days (of hub cost of goods)": "أيام المخزون (من تكلفة بضاعة الهب)", "Invite-only pilot: ~400 households, first-order vouchers.": "تجربة بالدعوة: حوالي 400 أسرة، قسائم أول طلب.",
 "Jan 2027": "يناير 2027", "Jan 2028": "يناير 2028", "Jun 2028, four months before the first expansion markaz.": "يونيو 2028، قبل أول مركز توسع بأربعة شهور.", "Launch Jan 2028: unlimited free delivery, double points.": "إطلاق يناير 2028: توصيل مجاني بلا حدود ونقاط مضاعفة.", "Launch op. month": "شهر الإطلاق التشغيلي",
 "Leadership & G&A (GM, finance, buyer, marketing, HR)": "الإدارة والمصروفات العمومية (مدير عام، مالية، مشتريات، تسويق، موارد بشرية)", "Leadership, G&A, office & legal": "الإدارة والمصروفات العمومية والمكتب والقانوني", "Lifetime contribution ÷ CAC (Y3)": "المساهمة مدى الحياة ÷ CAC (السنة 3)", "Lifetime contribution ÷ CAC, Year 3": "المساهمة مدى الحياة ÷ CAC، السنة الثالثة",
 "Local distributors typically give 14–30 days.": "الموزعون المحليون عادة بيدّوا 14–30 يوم.", "Local hiring, supplier onboarding, rider recruitment, launch kit.": "تعيين محلي وضم موردين وتعيين مناديب وعدة إطلاق.", "Local markaz team per live markaz (lead, ops, support)": "فريق المركز المحلي لكل مركز عامل (قائد وعمليات ودعم)", "Local markaz teams (expansion)": "فرق المراكز المحلية (التوسع)", "Local merchants, partner pharmacies": "التجار المحليون والصيدليات الشريكة",
 "Lowest cash balance with funding (must stay > 0)": "أقل رصيد نقدي مع التمويل (لازم يفضل > 0)", "Markaz (indicative — validate with demand data)": "المركز (استرشادي — يتأكد ببيانات الطلب)", "Markaz-level EBITDA (before central costs)": "EBITDA على مستوى المركز (قبل التكاليف المركزية)", "Markazes live (December)": "المراكز العاملة (ديسمبر)", "Markazes live (incl. Abu El Matamir)": "المراكز العاملة (شامل أبو المطامير)",
 "Marketplace & pharmacy": "السوق والصيدليات", "Marketplace & pharmacy commission": "عمولة السوق والصيدليات", "Marketplace commission": "عمولة السوق", "Maximum achievable penetration of reachable households": "أقصى اختراق ممكن للأسر في نطاق الوصول", "Members order more; their orders pay no delivery fee.": "المشتركون بيطلبوا أكتر؛ وطلباتهم من غير رسوم توصيل.",
 "Merchant & restaurant payables": "مستحقات التجار والمطاعم", "Merchant payout lag (marketplace & food)": "فترة تأخير تسوية التجار (السوق والأكل)", "Merchants (their own orders)": "التجار (طلباتهم الخاصة)", "Merchants' own orders delivered by Twaa riders. Starts operating month 4.": "طلبات التجار الخاصة يوصّلها مناديب توّا. تبدأ في الشهر التشغيلي 4.",
 "Metric": "المؤشر", "Minimum inventory per hub (SKU breadth)": "الحد الأدنى للمخزون لكل هب (اتساع الأصناف)", "Model start (first pre-launch month)": "بداية النموذج (أول شهر قبل الإطلاق)", "Month": "الشهر", "Monthly retention": "الاحتفاظ الشهري", "Monthly retention adjustment": "تعديل الاحتفاظ الشهري", "Monthly retention of active customers": "الاحتفاظ الشهري بالعملاء النشطين",
 "Multiplies average order value.": "يضرب في متوسط قيمة الطلب.", "Multiplies orders per active customer per month.": "يضرب في طلبات العميل النشط شهرياً.", "Multiplies yearly CAC.": "يضرب في CAC السنوي.", "Net income": "صافي الدخل", "Net revenue": "صافي الإيراد", "Net working capital": "صافي رأس المال العامل",
 "New customers acquired": "العملاء الجدد المكتسبون", "New customers — organic & referral": "العملاء الجدد — عضوي وإحالة", "New customers — paid": "العملاء الجدد — مدفوع", "New customers — total": "العملاء الجدد — الإجمالي", "Nominal, incl. ~12%/yr inflation and basket growth.": "اسمي، شامل تضخم حوالي 12% سنوياً ونمو السلة.", "Note": "ملاحظة", "Note / source": "ملاحظة / المصدر",
 "OTC pharmacy is fulfilled by licensed partner pharmacies.": "أدوية الصيدلية بدون روشتة تُنفّذ عبر صيدليات شريكة مرخّصة.", "Oct 2028 · adjacent markaz, shared supply routes": "أكتوبر 2028 · مركز مجاور وخطوط إمداد مشتركة", "Oct 2029": "أكتوبر 2029", "Oct 2030": "أكتوبر 2030",
 "Oct–Dec 2026 = pre-launch build. Jan 2027 = pilot (operating month 1). Feb 2027 = public launch.": "أكتوبر–ديسمبر 2026 = بناء ما قبل الإطلاق. يناير 2027 = التجربة (الشهر التشغيلي 1). فبراير 2027 = الإطلاق العام.", "Office, legal, accounting, insurance": "المكتب والقانوني والمحاسبة والتأمين",
 "Operating cash flow": "التدفق النقدي التشغيلي", "Operating expenses (incl. acquisition)": "المصروفات التشغيلية (شامل الاستحواذ)", "Operating flag": "مؤشر التشغيل", "Operating month (1 = Jan 2027 pilot)": "الشهر التشغيلي (1 = تجربة يناير 2027)", "Optimistic": "المتفائل", "Order frequency multiplier": "معامل تكرار الطلب", "Order frequency of members vs average": "تكرار طلب المشتركين مقابل المتوسط", "Orders & GMV": "الطلبات و GMV",
 "Orders per active customer per month": "طلبات العميل النشط شهرياً", "Orders per day (December)": "طلبات/يوم (ديسمبر)", "Organic & referral customers as % of paid": "العملاء العضويون والإحالة كنسبة من المدفوع", "Other variable (pick, pack, payments, shrink, refunds, support)": "متغيرة أخرى (تجميع، تغليف، دفع، هالك، استرداد، دعم)", "Packaging": "التغليف", "Packaging (branded bags, cold packs)": "التغليف (شنط بالعلامة وأكياس تبريد)",
 "Paid + promo acquisition; rises with each new village zone.": "استحواذ مدفوع وعروض؛ يزيد مع كل منطقة قرية جديدة.", "Paid Dec 2026.": "يُدفع ديسمبر 2026.", "Paid evenly Oct–Dec 2026. Prototype and BRD already done.": "يُدفع بالتساوي أكتوبر–ديسمبر 2026. النموذج الأولي ووثيقة المتطلبات جاهزين.", "Paid the month before opening.": "يُدفع في الشهر السابق للافتتاح.",
 "Payment gateway fee": "رسوم بوابة الدفع", "Payment gateway fees": "رسوم بوابة الدفع", "Peak funding need": "ذروة الاحتياج التمويلي", "Peak funding need (USD)": "ذروة الاحتياج التمويلي (دولار)", "Peak funding need (lowest cumulative free cash flow)": "ذروة الاحتياج التمويلي (أدنى تدفق نقدي حر تراكمي)", "Penetration of reachable households": "اختراق الأسر في نطاق الوصول",
 "Per customer order (EGP) — what one order earns and costs": "لكل طلب عميل (ج.م) — الطلب الواحد بيكسب كام وبيكلّف كام", "Per-drop pay model; batching offsets inflation.": "أجر بالتوصيلة؛ التجميع في رحلات يعادل التضخم.", "Phase": "المرحلة", "Pick & pack labour": "عمالة التجميع والتغليف", "Pick & pack labour per hub order": "عمالة التجميع والتغليف لكل طلب هب", "Pickers are variable (pick & pack).": "المجمّعون تكلفة متغيرة (تجميع وتغليف).",
 "Platform build (customer app, admin, picker, rider apps)": "بناء المنصة (تطبيق العميل والإدارة والمجمّع والمندوب)", "Population of Abu El Matamir markaz": "سكان مركز أبو المطامير", "Positive months so far": "الشهور الموجبة حتى الآن", "Pre-launch": "ما قبل الإطلاق", "Pre-launch cost per new markaz (one-off, month before launch)": "تكلفة ما قبل الإطلاق لكل مركز جديد (مرة واحدة، قبل الإطلاق بشهر)", "Pre-launch operating cost": "تكلفة التشغيل قبل الإطلاق", "Pre-launch operating cost (Oct–Dec 2026)": "تكلفة التشغيل قبل الإطلاق (أكتوبر–ديسمبر 2026)",
 "Pricing mechanism": "آلية التسعير", "Product margin": "هامش المنتجات", "Product margin (owned inventory)": "هامش المنتجات (مخزون مملوك)", "Public launch burst: flyers, WhatsApp groups, influencers, launch events, first-order 30% off.": "دفعة الإطلاق العام: فلاير وجروبات واتساب ومؤثرين وفعاليات إطلاق وخصم 30% على أول طلب.", "Referral 50 EGP give/get, word of mouth, rider branding.": "إحالة 50 ج.م لكل طرف، كلام الناس، تمييز المناديب.",
 "Refunds & compensation": "الاستردادات والتعويضات", "Rest are free via basket threshold or promotions.": "الباقي مجاني عبر حد السلة أو العروض.", "Restaurants": "المطاعم", "Retail margin after purchase cost. Egyptian grocery retail typically 12–20%; improves with volume buying and private label (2029+).": "هامش التجزئة بعد تكلفة الشراء. تجزئة البقالة في مصر عادة 12–20%؛ يتحسن مع الشراء بالكمية والعلامة الخاصة (2029+).",
 "Retail media": "إعلانات التطبيق", "Retail media (sponsored placement, in-app banners)": "إعلانات التطبيق (أماكن مدفوعة وبانرات)", "Revenue streams": "مصادر الإيراد", "Revenue streams — who pays, how it is priced, when it starts, what it earns (gross profit, EGP)": "مصادر الإيراد — مين بيدفع، التسعير، إمتى تبدأ، وبتكسب كام (مجمل الربح، ج.م)",
 "Rider (incl. split deliveries & DaaS drops)": "المندوب (شامل التسليم المجزّأ والتوصيل كخدمة)", "Rider cost": "تكلفة المندوب", "Rider cost per delivery (pay, fuel, phone, incentives)": "تكلفة المندوب للتوصيلة (أجر ووقود وتليفون وحوافز)", "Rider kit (thermal bags, helmets, phones) at launch": "عدة المناديب (شنط حرارية وخوذ وتليفونات) عند الإطلاق", "Rider supervision & dispatch": "الإشراف على المناديب والتوزيع", "Riders use own motorcycles (per-drop model).": "المناديب بيستخدموا موتوسيكلاتهم (أجر بالتوصيلة).",
 "Saturation factor (1 = open market)": "معامل التشبع (1 = سوق مفتوح)", "Saturation guard: new-customer acquisition slows linearly as penetration approaches this ceiling.": "حد التشبع: استحواذ العملاء الجدد يبطئ خطياً مع اقتراب الاختراق من السقف ده.", "Scenario multiplier": "معامل السيناريو", "Seed + growth rounds modelled": "جولتا البذرة والنمو في النموذج", "Seed round (received Oct 2026)": "جولة البذرة (تُستلم أكتوبر 2026)",
 "Selected scenario (1 = Conservative, 2 = Base, 3 = Optimistic)": "السيناريو المختار (1 = المتحفظ، 2 = الأساسي، 3 = المتفائل)", "Service fee": "رسوم الخدمة", "Service fee per order": "رسوم الخدمة للطلب", "Service fees": "رسوم الخدمة", "Set size > 0 to add a markaz": "حدد حجم > 0 لإضافة مركز", "Share 2031": "الحصة 2031",
 "Share of GMV paid digitally (cards, wallets)": "حصة GMV المدفوعة إلكترونياً (بطاقات ومحافظ)", "Share of households inside active delivery zones": "حصة الأسر داخل مناطق التوصيل المفعّلة", "Share of last month's active customers who order again this month.": "نسبة العملاء النشطين الشهر اللي فات اللي طلبوا تاني الشهر ده.", "Share of orders paying delivery fee (before Twaa+)": "حصة الطلبات اللي بتدفع رسوم توصيل (قبل توّا+)",
 "Shrinkage, expiry & damage": "الهالك وانتهاء الصلاحية والتلف", "Size vs Abu El Matamir": "الحجم مقابل أبو المطامير", "Small fixed fee shown transparently at checkout.": "رسوم ثابتة صغيرة ظاهرة بوضوح عند الدفع.", "Split deliveries when components can't be consolidated.": "التسليم المجزّأ لما المكونات ما ينفعش تتجمع.", "Sponsored slots, banners: 0.3% → 2% of hub GMV": "أماكن مدفوعة وبانرات: 0.3% ← 2% من GMV الهب",
 "Starts": "يبدأ", "Stream": "المصدر", "Supplier back margin": "حوافز الموردين", "Supplier back margin (rebates, listing fees)": "حوافز الموردين (خصومات ورسوم إدراج)", "Supplier credit days": "أيام ائتمان الموردين", "Supplier payables": "مستحقات الموردين", "Support & messaging": "الدعم والرسائل", "Support, SMS & WhatsApp per order": "الدعم والرسائل وواتساب لكل طلب",
 "Sustain launch momentum, start village teasers.": "الحفاظ على زخم الإطلاق وبدء التشويق في القرى.", "Take rate (GP % GMV)": "نسبة الاستقطاع (مجمل الربح % من GMV)", "Taxable profit after losses": "الربح الخاضع للضريبة بعد الخسائر", "Technology team & infrastructure": "فريق التقنية والبنية التحتية", "Technology team / vendor retainer": "فريق التقنية / عقد مورّد", "Timeline": "الجدول الزمني",
 "Top-up behaviour: bread, milk, water, diapers several times a week.": "سلوك الطلبات التكميلية: عيش ولبن ومياه وحفاضات أكتر من مرة في الأسبوع.", "Total capex": "إجمالي الإنفاق الرأسمالي", "Total gross profit": "إجمالي مجمل الربح", "Total operating expenses (excl. variable)": "إجمالي المصروفات التشغيلية (بدون المتغيرة)", "Total variable costs": "إجمالي التكاليف المتغيرة",
 "Twaa+": "توّا+", "Twaa+ (allocated per order)": "توّا+ (موزعة على الطلب)", "Twaa+ members as % of active customers": "مشتركو توّا+ كنسبة من العملاء النشطين", "Twaa+ subscription": "اشتراك توّا+", "Twaa+ subscription price": "سعر اشتراك توّا+", "Typical Egyptian gateway MDR; confirm with Paymob/Fawry/Geidea quote.": "عمولة بوابة الدفع المعتادة في مصر؛ تتأكد بعرض سعر من Paymob أو Fawry أو Geidea.",
 "Unit": "الوحدة", "Useful life — hub equipment": "العمر الإنتاجي — معدات الهب", "Useful life — technology": "العمر الإنتاجي — التقنية", "Value": "القيمة", "Variable costs": "التكاليف المتغيرة", "Variable costs per order": "التكاليف المتغيرة لكل طلب", "Village micro-hub fit-out (hub 2 and hub 3, each)": "تجهيز هب القرية الصغير (الهب 2 والهب 3، لكل واحد)",
 "Volume rebates from distributors/brands once volume is proven.": "خصومات كمية من الموزعين والعلامات بعد إثبات الحجم.", "Volume rebates, listing fees: up to 3% of hub GMV": "خصومات كمية ورسوم إدراج: حتى 3% من GMV الهب", "Weekly settlement: cash float in Twaa's favour.": "تسوية أسبوعية: سيولة لصالح توّا.", "Who pays": "مين بيدفع", "Working capital & cash": "رأس المال العامل والنقدية",
 "Year": "السنة", "Year 1": "السنة 1", "Year 2": "السنة 2", "Year 3": "السنة 3", "Year 4": "السنة 4", "Year 5": "السنة 5", "date": "التاريخ", "days": "يوم", "deliveries/day": "توصيلة/يوم", "months": "شهر", "orders": "طلب", "people": "نسمة", "pp": "نقطة", "x": "×",
 "~1,500–3,000 SKUs at launch.": "حوالي 1,500–3,000 صنف عند الإطلاق.",
 "توّا Twaa — Annual summary (EGP, nominal)": "توّا — الملخص السنوي (ج.م، اسمي)", "توّا Twaa — Assumptions (all inputs live here)": "توّا — الافتراضات (كل المدخلات هنا)", "توّا Twaa — Financial model summary": "توّا — ملخص النموذج المالي", "توّا Twaa — Monthly model Oct 2026 – Dec 2031 (formulas only; edit Assumptions)": "توّا — النموذج الشهري أكتوبر 2026 – ديسمبر 2031 (معادلات فقط؛ عدّل الافتراضات)",
 "Cash balance": "رصيد النقدية",
}
# per-markaz rows: "<label> — <English> — <Arabic>" → "<label translated> — <Arabic>"
PREFIX = {"Acquisition spend": "إنفاق الاستحواذ", "Active customers": "العملاء النشطون", "Orders": "الطلبات"}
LITERALS = {"Scenario: ": "السيناريو: ", "Conservative": "المتحفظ", "Base": "الأساسي", "Optimistic": "المتفائل", "OK": "سليم", "ERROR": "خطأ", "Pre-launch": "ما قبل الإطلاق", "Pilot": "تجربة", "City": "المدينة", "Villages I": "القرى", "Multi-markaz": "متعدد المراكز", "Not within horizon": "خارج الأفق الزمني", "OK — funded": "سليم — ممول", "SHORTFALL — raise more": "عجز — مطلوب تمويل إضافي"}
CHART_TITLES = {"Gross profit by revenue stream (EGP)": "مجمل الربح حسب مصدر الإيراد (ج.م)", "Customer orders per day": "طلبات العملاء في اليوم", "Cash balance (EGP) and monthly EBITDA": "رصيد النقدية (ج.م) و EBITDA الشهرية"}

def tr(s):
    if s in T: return T[s]
    m = re.match(r"^(.*?) — (.+?) — (.+)$", s)
    if m and m.group(1) in PREFIX: return f"{PREFIX[m.group(1)]} — {m.group(3)}"
    m = re.match(r"^(.*?) — \(spare slot\)$", s)
    if m and m.group(1) in PREFIX: return f"{PREFIX[m.group(1)]} — (خانة احتياطية)"
    m = re.match(r"^2\. Switch scenario on Assumptions!C(\d+): 1 Conservative · 2 Base · 3 Optimistic\.$", s)
    if m: return f"2. بدّل السيناريو من خلية الافتراضات!C{m.group(1)}: 1 المتحفظ · 2 الأساسي · 3 المتفائل."
    return s

def fix_formula(f):
    def lit(m):
        v = m.group(1)
        if v in LITERALS: return '"' + LITERALS[v] + '"'
        mm = re.match(r"^   ·   Change it on Assumptions!C(\d+)   ·   EGP, nominal, ex-VAT$", v)
        if mm: return f'"   ·   غيّره من الافتراضات!C{mm.group(1)}   ·   جنيه اسمي بدون ض.ق.م"'
        return m.group(0)
    f = re.sub(r'"([^"]*)"', lit, f)
    parts = re.split(r'("[^"]*")', f)   # never rewrite inside string literals
    for i in range(0, len(parts), 2):
        for en, ar in SHEETS.items():
            parts[i] = parts[i].replace(f"'{en}'!", f"'{ar}'!")
            parts[i] = re.sub(rf"(?<![\w']){re.escape(en)}!", f"'{ar}'!", parts[i])
    return "".join(parts)

def apply(wb):
    from openpyxl.chart.series import SeriesLabel
    missing = set()
    for ws in wb.worksheets:
        for row in ws.iter_rows():
            for c in row:
                v = c.value
                if isinstance(v, str):
                    if v.startswith("="): c.value = fix_formula(v)
                    else:
                        t = tr(v)
                        if t == v and re.search(r"[A-Za-z]{3,}", v) and v not in ("EBIT", "EBITDA", "GMV", "DaaS"): missing.add(v)
                        c.value = t
                if c.number_format and '" mo"' in c.number_format: c.number_format = c.number_format.replace('" mo"', '" شهر"')
        for dv in ws.data_validations.dataValidation:
            if dv.formula1: dv.formula1 = fix_formula(dv.formula1)
        ws.sheet_view.rightToLeft = True
        for ch in ws._charts:
            try:
                t = ch.title.tx.rich.p[0].r[0].t
                ch.title = CHART_TITLES.get(t, t)
            except Exception:
                pass
            for s in ch.series:
                if s.tx is not None and getattr(s.tx, "v", None): s.tx = SeriesLabel(v=tr(s.tx.v) if tr(s.tx.v) != s.tx.v else T.get(s.tx.v, s.tx.v))
    for dn in list(wb.defined_names.values()) if hasattr(wb.defined_names, "values") else []:
        if dn.attr_text: dn.attr_text = fix_formula(dn.attr_text)
    for ws in wb.worksheets:
        if ws.title in SHEETS: ws.title = SHEETS[ws.title]
    return missing
