/* Swimlane renderer: explicit lane + column placement, orthogonal edges, RTL columns */
const { COL, esc, wrap } = require("./engine");
const LANES = ["العميل", "تطبيق / منصة توّا", "OMS ومحرك العمليات", "هب توّا", "التاجر / المطعم", "الرايدر", "الدفع والمالية", "خدمة العملاء / Control Tower"];
const LANE_FILL = ["#FFFFFF", "#F6F0F7", "#EFE7F9", "#F9F2E7", "#FBF3EA", "#FFF3EC", "#EEF4F1", "#F3EEF3"];
function renderSwim(sw) {
  const colW = 158, laneH = 104, head = 34, labelW = 118, bw = 138, bh = 74; const ncol = Math.max(...sw.nodes.map((n) => n.col)) + 1;
  const W = labelW + ncol * colW + 10, H = head + LANES.length * laneH + 10;
  const cx = (col) => W - labelW - (col + 0.5) * colW; /* RTL: col 0 at right, lane label on the right */
  const cy = (lane) => head + lane * laneH + laneH / 2;
  let out = "";
  LANES.forEach((l, i) => { out += `<rect x="0" y="${head + i * laneH}" width="${W}" height="${laneH}" fill="${LANE_FILL[i]}" stroke="${COL.line}" stroke-width="1"/><rect x="${W - labelW}" y="${head + i * laneH}" width="${labelW}" height="${laneH}" fill="${COL.plum}"/>`; wrap(l, 14).forEach((ln, k, arr) => { out += `<text x="${W - labelW / 2}" y="${cy(i) - ((arr.length - 1) * 15) / 2 + k * 15}" font-size="12.5" font-weight="700" fill="${COL.cream}" text-anchor="middle" dominant-baseline="middle" direction="rtl">${esc(ln)}</text>`; }); });
  out += `<rect x="0" y="0" width="${W}" height="${head}" fill="${COL.cream}"/><text x="${W - 8}" y="${head / 2}" font-size="13" font-weight="700" fill="${COL.plum}" text-anchor="end" dominant-baseline="middle" direction="rtl">${esc(sw.title)}</text>`;
  const pos = {}; sw.nodes.forEach((n) => { pos[n.id] = { x: cx(n.col), y: cy(n.lane), n }; });
  /* edges */
  for (const e of sw.edges) { const a = pos[e.from], b = pos[e.to]; if (!a || !b) throw new Error("swim edge " + e.from + "->" + e.to); const c = { ok: COL.green, fail: COL.red, wait: COL.orange, sys: COL.purple }[e.cls] || COL.plum2; let d, lx, ly;
    const dir = b.x < a.x ? -1 : 1; /* -1 = forward (leftwards) */
    if (a.n.lane === b.n.lane) { const x1 = a.x + dir * bw / 2, x2 = b.x - dir * bw / 2; if (Math.abs(b.n.col - a.n.col) > 1) { const yy = a.y - bh / 2 - 10; d = `M${a.x} ${a.y - bh / 2} L${a.x} ${yy} L${b.x} ${yy} L${b.x} ${b.y - bh / 2}`; lx = (a.x + b.x) / 2; ly = yy - 8; } else { d = `M${x1} ${a.y} L${x2} ${b.y}`; lx = (x1 + x2) / 2; ly = a.y - 10; } }
    else { const down = b.y > a.y; const y1 = a.y + (down ? bh / 2 : -bh / 2); const x2 = b.x - dir * bw / 2; if (Math.abs(b.x - a.x) < 4) { d = `M${a.x} ${y1} L${b.x} ${b.y + (down ? -bh / 2 : bh / 2)}`; lx = a.x + 12; ly = (y1 + b.y) / 2; } else { d = `M${a.x} ${y1} L${a.x} ${b.y} L${x2} ${b.y}`; lx = (a.x + x2) / 2; ly = b.y - 10; } }
    out += `<path d="${d}" fill="none" stroke="${c}" stroke-width="${e.cls === "fail" || e.cls === "ok" ? 2 : 1.5}" ${e.cls === "wait" ? 'stroke-dasharray="7 4"' : ""} marker-end="url(#sw-${e.cls || "d"})"/>`;
    if (e.label) { const lw = e.label.length * 6.5 + 10; out += `<rect x="${lx - lw / 2}" y="${ly - 8}" width="${lw}" height="16" rx="8" fill="#fff" stroke="${c}"/><text x="${lx}" y="${ly + 1}" font-size="10" font-weight="700" fill="${c}" text-anchor="middle" dominant-baseline="middle" direction="rtl">${esc(e.label)}</text>`; } }
  /* nodes */
  for (const n of sw.nodes) { const p = pos[n.id]; const x = p.x - bw / 2, y = p.y - bh / 2; const t = n.type || "P"; const lines = wrap(n.label, 19).slice(0, 3);
    const F = { S: [COL.plum, COL.plum, COL.white], E: [n.cls === "fail" ? COL.red : n.cls === "ok" ? COL.green : COL.gray, "none", COL.white], D: [COL.white, COL.orange, COL.ink], X: [COL.purple2, COL.purple, COL.ink], W: ["#FFF3EC", COL.orange, COL.ink], P: [COL.white, COL.plum, COL.ink] }[t] || [COL.white, COL.plum, COL.ink];
    if (t === "D") out += `<polygon points="${p.x},${y - 4} ${x + bw + 6},${p.y} ${p.x},${y + bh + 4} ${x - 6},${p.y}" fill="${F[0]}" stroke="${F[1]}" stroke-width="2"/>`;
    else if (t === "S" || t === "E") out += `<rect x="${x}" y="${y + 8}" width="${bw}" height="${bh - 16}" rx="${(bh - 16) / 2}" fill="${F[0]}" stroke="${F[1]}"/>`;
    else out += `<rect x="${x}" y="${y}" width="${bw}" height="${bh}" rx="3" fill="${F[0]}" stroke="${F[1]}" stroke-width="1.6" ${t === "W" ? 'stroke-dasharray="6 3"' : ""}/>`;
    const ty = p.y - ((lines.length - 1) * 14) / 2 - (n.code ? 6 : 0);
    lines.forEach((l, i) => { out += `<text x="${p.x}" y="${ty + i * 14}" font-size="11.5" font-weight="600" fill="${F[2]}" text-anchor="middle" dominant-baseline="middle" direction="rtl">${esc(l)}</text>`; });
    if (n.code) out += `<text x="${p.x}" y="${ty + lines.length * 14 - 1}" font-size="8.5" fill="${F[2] === COL.white ? "#F3E8F3" : COL.gray}" text-anchor="middle" dominant-baseline="middle" direction="ltr" font-family="Consolas,'DejaVu Sans Mono',monospace">${esc(n.code)}</text>`;
    if (n.ref) out += `<text x="${x + bw}" y="${y - 4}" font-size="9" fill="${COL.purple}" text-anchor="end" font-weight="700" direction="ltr">${esc(n.ref)}</text>`; }
  const defs = `<defs>${Object.entries({ ok: COL.green, fail: COL.red, wait: COL.orange, sys: COL.purple, d: COL.plum2 }).map(([k, c]) => `<marker id="sw-${k}" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse"><path d="M0 0L10 5L0 10z" fill="${c}"/></marker>`).join("")}</defs>`;
  return { svg: `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${W} ${H}" class="swim" font-family="Cairo,'Noto Sans Arabic',sans-serif">${defs}${out}</svg>`, w: W, h: H };
}
/* ---------- Swimlane data (4 connected boards) ---------- */
const N = (id, lane, col, label, type = "P", code = "", cls = "", ref = "") => ({ id, lane, col, label, type, code, cls, ref });
const E = (from, to, label = "", cls = "") => ({ from, to, label, cls });
const boards = [
  { title: "اللوحة A — من فتح التطبيق إلى إنشاء الطلب وتقسيمه (P01–P08)", nodes: [
    N("a1", 0, 0, "يفتح توّا", "S"), N("a2", 1, 1, "اكتشاف الموقع / اختيار يدوي", "P", "GEO_DETECT", "", "P01"), N("a3", 2, 2, "فحص نطاق الخدمة", "X", "SERVICEABILITY_CHECK"), N("a4", 1, 3, "داخل النطاق؟", "D"), N("a5", 1, 4, "عرض الانتظار + تسجيل الطلب", "W", "WAITLIST"), N("a6", 0, 5, "خارج النطاق", "E", "OUTSIDE_SERVICE_AREA", "fail"),
    N("a7", 0, 4, "يتصفح ويبحث ويضيف للسلة", "P", "", "", "P02–P03"), N("a8", 2, 5, "تحديد مصدر كل بند + دمج المصادر", "X", "ITEM_SOURCE"), N("a9", 1, 6, "عرض السلة حسب المصدر + ETA", "P", "CART_VIEW"), N("a10", 0, 7, "إتمام الطلب", "P"), N("a11", 2, 8, "إعادة التحقق الشاملة", "X", "PRE_CHECKOUT_VALIDATION", "", "P04"), N("a12", 1, 9, "السلة صالحة؟", "D"), N("a13", 0, 10, "يصحّح السلة / يترك", "W"),
    N("a14", 0, 9, "يؤكد العنوان والدفع", "P", "", "", "P05"), N("a15", 6, 10, "دفع أونلاين / أهلية كاش", "X", "PAYMENT / COD_ELIGIBILITY", "", "P06"), N("a16", 6, 11, "نجح؟", "D"), N("a17", 6, 12, "تسوية دفع مطلوبة", "W", "PAYMENT_RECONCILIATION"), N("a18", 2, 12, "إنشاء الطلب + لقطة + أوامر التنفيذ", "X", "CREATED → ALLOCATED", "", "P07–P08"), N("a19", 1, 13, "إشعار: تم تأكيد طلبك", "X", "NOTIFY"), N("a20", 3, 13, "FO هب → P09/P11", "P", "FO_HUB"), N("a21", 4, 13, "FO تاجر → P09/P13", "P", "FO_MERCHANT"), N("a22", 7, 12, "متابعة حالات التسوية", "W", "CONTROL_TOWER"),
  ], edges: [E("a1", "a2"), E("a2", "a3", "", "sys"), E("a3", "a4"), E("a4", "a7", "نعم", "ok"), E("a4", "a5", "لا", "fail"), E("a5", "a6", "", "fail"), E("a7", "a8", "", "sys"), E("a8", "a9"), E("a9", "a10"), E("a10", "a11", "", "sys"), E("a11", "a12"), E("a12", "a14", "نعم", "ok"), E("a12", "a13", "لا", "fail"), E("a13", "a11", "تصحيح"), E("a14", "a15", "", "sys"), E("a15", "a16"), E("a16", "a18", "نعم", "ok"), E("a16", "a17", "معلّق", "wait"), E("a17", "a22", "", "wait"), E("a17", "a18", "الدفع مؤكد"), E("a18", "a19", "", "sys"), E("a18", "a20", "", "sys"), E("a18", "a21", "", "sys")] },
  { title: "اللوحة B — التنفيذ: الهب والتاجر حتى الجاهزية (P09–P13)", nodes: [
    N("b1", 2, 0, "أمر تنفيذ نشط", "S", "ALLOCATED"), N("b2", 3, 1, "مخزون النظام متاح؟ → حجز", "D", "", "", "P09"), N("b3", 3, 2, "تجميع بالمسح: صنف / كمية / جودة", "P", "PICKING", "", "P11"), N("b4", 3, 3, "الرف فاضي؟", "D"), N("b5", 3, 4, "عدم تطابق مخزون → عد/موقع بديل", "W", "INVENTORY_MISMATCH"), N("b6", 2, 5, "الاستبدال: تلقائي / اسألني / حذف", "X", "SUBSTITUTION", "", "P10"), N("b7", 0, 6, "يرد على البديل خلال المهلة", "W", "AWAITING_CUSTOMER_DECISION"), N("b8", 2, 7, "تطبيق الاختيار / الاحتياطي + إعادة الحساب", "X", "SUBSTITUTION_APPLIED"), N("b9", 6, 8, "تسجيل فرق السعر للتسوية", "X", "SUBSTITUTION_RECONCILED"),
    N("b10", 3, 8, "تغليف + باركود طرد + ملصق كاش", "P", "READY_FOR_DISPATCH", "", "P12"),
    N("b11", 4, 1, "استقبال الأمر + مؤقت القبول", "X", "MERCHANT_ORDER_SENT"), N("b12", 4, 2, "رد التاجر؟", "D"), N("b13", 7, 3, "اتصال بالتاجر عند انتهاء المهلة", "W", "MERCHANT_TIMEOUT"), N("b14", 2, 4, "إعادة توجيه لبديل / إلغاء المكوّن", "X", "FO_REROUTED / CANCELLED"), N("b15", 4, 5, "التجهيز + مؤقت SLA", "P", "PREPARING", "", "P13"), N("b16", 4, 6, "جاهز خلال SLA؟", "D"), N("b17", 7, 7, "تأخير: تحديث ETA + اتصال + قرار", "W", "PREPARATION_DELAYED"), N("b18", 1, 8, "إشعار العميل بالتأخير / التغيير", "X", "NOTIFY_DELAYED"), N("b19", 4, 9, "جاهز للاستلام", "P", "READY_FOR_PICKUP"),
    N("b20", 2, 10, "أمر التنفيذ جاهز → P14", "E", "READY", "ok"), N("b21", 2, 6, "إلغاء لعدم التوافر", "E", "OUT_OF_STOCK_CANCELLED", "fail"),
  ], edges: [E("b1", "b2"), E("b1", "b11", "", "sys"), E("b2", "b3", "نعم"), E("b2", "b6", "لا", "fail"), E("b3", "b4"), E("b4", "b10", "لا", "ok"), E("b4", "b5", "نعم", "fail"), E("b5", "b3", "اتلقى"), E("b5", "b6", "لم يُلقَ", "fail"), E("b6", "b7", "اسألني", "wait"), E("b6", "b8", "تلقائي/حذف"), E("b7", "b8", "رد/مهلة"), E("b8", "b9", "", "sys"), E("b8", "b10", "يحقق الحد"), E("b8", "b21", "تحت الحد", "fail"), E("b10", "b20", "", "ok"), E("b11", "b12"), E("b12", "b15", "قبول", "ok"), E("b12", "b13", "لا رد", "wait"), E("b12", "b14", "رفض", "fail"), E("b12", "b6", "جزئي", "wait"), E("b13", "b15", "أكّد"), E("b13", "b14", "لم يرد", "fail"), E("b14", "b11", "بديل"), E("b14", "b21", "لا بديل", "fail"), E("b15", "b16"), E("b16", "b19", "نعم", "ok"), E("b16", "b17", "لا", "fail"), E("b17", "b18"), E("b17", "b15", "يستمر"), E("b17", "b14", "إعادة توجيه/إلغاء", "fail"), E("b19", "b20", "", "ok")] },
  { title: "اللوحة C — التوصيل: من محرك التنسيق إلى إثبات التسليم (P14–P20)", nodes: [
    N("c1", 2, 0, "خطة التسليم: واحد / متعدد / مجمّع / مجدول", "X", "DELIVERY_TASKS_CREATED", "", "P14"), N("c2", 2, 1, "ترشيح رايدر + عرض المهمة", "X", "OFFER_SENT", "", "P15"), N("c3", 5, 2, "قبول / رفض / مهلة", "D"), N("c4", 7, 3, "لا رايدر: تمديد / بديل / إلغاء", "W", "RIDER_UNAVAILABLE"), N("c5", 1, 3, "إشعار: تم تعيين المندوب", "X", "NOTIFY_RIDER_ASSIGNED"),
    N("c6", 5, 4, "الوصول لنقطة الاستلام + مسح الطرود", "P", "", "", "P16"), N("c7", 3, 5, "الهب: تحقق هوية + عدد + حالة → نقل حيازة", "X", "CUSTODY_TRANSFERRED"), N("c8", 4, 5, "التاجر: تأكيد التسليم للرايدر", "X", "CUSTODY_TRANSFERRED"), N("c9", 5, 6, "في الطريق + تتبع حي", "P", "IN_TRANSIT", "", "P17"), N("c10", 7, 7, "استثناء طريق: عطل / تلف / تغيير عنوان", "W", "RIDER_RESCUE / DELAYED"), N("c11", 1, 7, "إشعار: المندوب قرّب", "X", "NOTIFY_APPROACHING"),
    N("c12", 5, 8, "وصل: العميل موجود؟", "D", "ARRIVED", "", "P18"), N("c13", 0, 9, "يستلم / يرد على الاتصال", "P"), N("c14", 7, 9, "اتصال بالعميل والرقم البديل", "W", "CUSTOMER_UNREACHABLE"), N("c15", 5, 10, "تحصيل الكاش / رابط دفع", "P", "COD_COLLECTED", "", "P19"), N("c16", 6, 10, "تسجيل المتوقع والمحصّل في رصيد الرايدر", "X", "RIDER_CASH_BALANCE"), N("c17", 0, 11, "كود الاستلام OTP / تأكيد", "P", "", "", "P20"), N("c18", 2, 12, "نتيجة التسليم", "D"), N("c19", 2, 13, "تم التوصيل → P24", "E", "DELIVERED", "ok"), N("c20", 2, 14, "فشل / استثناء → P21", "E", "DELIVERY_FAILED", "fail"), N("c21", 1, 13, "إشعار: وصلك + طلب التقييم", "X", "NOTIFY_DELIVERED"),
  ], edges: [E("c1", "c2", "", "sys"), E("c2", "c3"), E("c3", "c6", "قبول", "ok"), E("c3", "c2", "رفض/مهلة", "fail"), E("c3", "c4", "تجاوز المحاولات", "wait"), E("c4", "c2", "إعادة"), E("c3", "c5", "قبول", "sys"), E("c6", "c7"), E("c6", "c8"), E("c7", "c9", "", "sys"), E("c8", "c9", "", "sys"), E("c9", "c10", "استثناء", "fail"), E("c10", "c9", "بعد الحل"), E("c9", "c11", "", "sys"), E("c9", "c12"), E("c12", "c13", "نعم", "ok"), E("c12", "c14", "لا", "fail"), E("c14", "c13", "تم الوصول"), E("c14", "c20", "لا رد", "fail"), E("c13", "c15"), E("c15", "c16", "", "sys"), E("c15", "c17", "تم الدفع", "ok"), E("c15", "c20", "لم يدفع", "fail"), E("c17", "c18"), E("c18", "c19", "كامل", "ok"), E("c18", "c20", "رفض/تالف/ناقص", "fail"), E("c19", "c21", "", "sys")] },
  { title: "اللوحة D — الاستثناءات والإغلاق: فشل التسليم، الإرجاع، الإلغاء، الاسترداد، التسوية، الدعم (P21–P25)", nodes: [
    N("d1", 7, 0, "فشل تسليم: تحديد السبب والمسؤول", "D", "DELIVERY_FAILED", "", "P21"), N("d2", 0, 1, "إعادة محاولة بموعد", "W", "REATTEMPT"), N("d3", 5, 1, "إرجاع للأصل", "P", "RETURN_TO_ORIGIN", "", "P22"), N("d4", 3, 2, "الهب: مسح مرتجع + فحص + إعادة للمخزون / هالك", "X", "RETURNED / RESTOCKED"), N("d5", 4, 2, "التاجر: يستلم المرتجع أو ينازع", "P", "RETURNED_TO_MERCHANT"), N("d6", 6, 3, "تحديث الالتزام المالي: من يتحمل", "X", "LIABILITY_UPDATED"),
    N("d7", 0, 4, "طلب إلغاء / استرداد / شكوى", "P", "", "", "P23 / P25"), N("d8", 2, 5, "حالة الطلب تسمح بالإلغاء؟", "D"), N("d9", 2, 6, "تحرير الحجوزات / إيقاف المهام", "X", "RESOURCES_RELEASED"), N("d10", 7, 5, "موافقة الدعم (أثناء التجهيز)", "W", "CANCEL_APPROVAL"), N("d11", 6, 7, "حالة إرجاع مالي: المسؤول + المبلغ + مستوى الموافقة", "X", "REFUND_CASE"), N("d12", 6, 8, "تنفيذ الإرجاع: بوابة / تحويل / محفظة", "X", "REFUND_TRACKED"), N("d13", 1, 9, "إشعار: تم رد المبلغ", "X", "NOTIFY_REFUNDED"),
    N("d14", 6, 10, "دفتر الطلب: عميل / تاجر / رايدر / توّا / كاش", "X", "ORDER_LEDGER", "", "P24"), N("d15", 6, 11, "مطابقة الكاش والدفع والإرجاع", "D", "RECONCILED"), N("d16", 7, 12, "فرق كاش / فرق مالي: تحقيق", "W", "COD_DISCREPANCY"), N("d17", 4, 12, "كشف تسوية التاجر", "X", "MERCHANT_SETTLEMENT"), N("d18", 5, 12, "كشف تسوية الرايدر", "X", "RIDER_SETTLEMENT"), N("d19", 6, 13, "إغلاق مالي", "E", "FINANCIALLY_CLOSED", "ok"),
    N("d20", 1, 1, "إشعار التقييم بعد التسليم", "X", "RATING_REQUEST", "", "P25"), N("d21", 0, 2, "يقيّم / يشتكي", "P"), N("d22", 7, 3, "حالة دعم: تحقيق + رد خلال SLA", "W", "SUPPORT_CASE"), N("d23", 2, 3, "تحديث CRM + عروض/إحالة", "X", "CRM_UPDATED"),
  ], edges: [E("d1", "d2", "إعادة محاولة", "wait"), E("d1", "d3", "إرجاع", "fail"), E("d1", "d11", "إرجاع مالي"), E("d3", "d4"), E("d3", "d5"), E("d4", "d6", "", "sys"), E("d5", "d6", "", "sys"), E("d6", "d14", "", "sys"), E("d7", "d8"), E("d8", "d9", "نعم", "ok"), E("d8", "d10", "أثناء التجهيز", "wait"), E("d10", "d9", "موافقة"), E("d9", "d11", "مدفوع"), E("d9", "d14", "غير مدفوع", "sys"), E("d11", "d12"), E("d12", "d13", "", "sys"), E("d12", "d14", "", "sys"), E("d14", "d15"), E("d15", "d17", "نعم", "ok"), E("d15", "d18", "نعم", "ok"), E("d15", "d16", "لا", "fail"), E("d16", "d15", "بعد التصحيح"), E("d17", "d19"), E("d18", "d19"), E("d20", "d21"), E("d21", "d22", "شكوى/تقييم منخفض", "fail"), E("d21", "d23", "تقييم", "ok"), E("d22", "d11", "استرداد"), E("d22", "d23", "مغلق")] },
];
module.exports = { renderSwim, boards, LANES };
